{% set name = "roman" %}
{% set version = "5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/roman-{{ version }}.tar.gz
  sha256: cb35293c1c4046105fd899194f4f2985f78c955a8b05937f7ab93f3be1660697

build:
  number: 0
  noarch: python
  entry_points:
    - roman=roman:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - python >={{ python_min }}

test:
  imports:
    - roman
  commands:
    - pip check
    - roman --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/zopefoundation/roman
  license: Python-2.0
  license_file: LICENSE.txt
  summary: Integer to Roman numerals converter
  description: |
    roman is a Small helper library to convert arabic to roman numerals.
    There are two ways to use this library: Importing it into your application; and the roman CLI command.

extra:
  recipe-maintainers:
    - thewchan
