{% set name = "roman" %}
{% set version = "4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/roman-{{ version }}.tar.gz
  sha256: 6caab7ba51b83c46b5bf8839e5d782769a6b08fdea8abdfa62a4197c041fd513

build:
  number: 0
  noarch: python
  entry_points:
    - roman=roman:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.5
  run:
    - python >=3.5

test:
  imports:
    - roman
  commands:
    - pip check
    - roman --help
  requires:
    - pip

about:
  home: https://github.com/zopefoundation/roman
  license: Python-2.0`
  license_file: LICENSE.txt
  summary: Integer to Roman numerals converter
  description: |
    roman is a Small helper library to convert arabic to roman numerals.
    There are two ways to use this library: Importing it into your application; and the roman CLI command.

extra:
  recipe-maintainers:
    - thewchan
