{% set name = "roman" %}
{% set version = "5.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/roman-{{ version }}.tar.gz
  sha256: 3a86572e9bc9183e771769601189e5fa32f1620ffeceebb9eca836affb409986

build:
  number: 0
  noarch: python
  entry_points:
    - roman=roman:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools ==78.1.1
    - wheel
  run:
    - python >={{ python_min }}

test:
  imports:
    - roman
  commands:
    - pip check
    - roman --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/zopefoundation/roman
  license: Python-2.0
  license_file: LICENSE.txt
  summary: Integer to Roman numerals converter
  description: |
    roman is a Small helper library to convert arabic to roman numerals.
    There are two ways to use this library: Importing it into your application; and the roman CLI command.

extra:
  recipe-maintainers:
    - thewchan
